name: publish-context-values
on: push
env:
  JOB_ID: "${{ github.event.run_id }}"
  BRANCH: "${{ github.event.ref }}"
  

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Print job id
        run: echo "${{ env.JOB_ID }}"
        
      - name: Set ENV
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
        
      - name: Print Branch
        run: echo "$BRANCH_NAME"  
    
