name: publish-context-values
on: push
env:
  JOB_ID: "${{ github.event.run_id }}"
  BRANCH: "${{ github.event.ref }}"
  

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Print job id
        run: echo "${{ env.JOB_ID }}"
        
      - name: Set ENV
        run: |
          echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
          echo "::set-env name=S3_BUCKET_NAME_D::$(echo docssite-$BRANCH_NAME${{ github.run_number }}"
        
      - name: Print Branch
        run: echo "$BRANCH_NAME"  
      
      - name: Print Bucket names
        env:
          S3_BUCKET_NAME_D      : "docssite-${BRANCH_NAME}${{ github.run_number }}"
          S3_BUCKET_NAME_S      : "storybook-${BRANCH_NAME}${{ github.run_number }}"
        run: |
          echo "${{ env.S3_BUCKET_NAME_D }}
          echo "${{ env.S3_BUCKET_NAME_S }}

      - name: Print Bucket names in new step
        run: |
          echo "${{ env.S3_BUCKET_NAME_D }}
          echo "${{ env.S3_BUCKET_NAME_S }}
