name: Test-teardown
env: 
  S3_BUCKET_NAME      : "${{ github.sha }}"
  DEPLOY_PACKAGE_NAME : "packages/docs-site/public"
  AWS_REGION_NAME     : "eu-west-2"
  BRANCH              : "${{ github.ref }}"

on:
  delete:
#    branches: 
#      - master
jobs:        
     docs-site_teardown_pipeline:
      runs-on: ubuntu-latest
      
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2  
          
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
          
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: echo "$JOB_CONTEXT"         
                   
        - name: Print branchname
          run:  echo "${{env.BRANCH}}"
          
        - name: Print action   
          run: echo "Im going to remove the resources related to ${{env.BRANCH}}"

    
    
